import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { googleIdentity } from './security.js';
test('Google header requires Azure hosting and Google identity',()=>{
 const headers={'x-ms-client-principal':Buffer.from(JSON.stringify({auth_typ:'google',claims:[{typ:'sub',val:'test-subject'},{typ:'email',val:'test@example.com'}]})).toString('base64')};
 assert.equal(googleIdentity(headers,{NODE_ENV:'production'}),null);
 assert.deepEqual(googleIdentity(headers,{NODE_ENV:'production',WEBSITE_SITE_NAME:'test'}),{subject:'test-subject',email:'test@example.com'});
});
test('private session, workout conflicts and reconnect recovery',async()=>{
 process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'steady-test-'));
 const {server}=await import('./server.js');
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 let base='http://127.0.0.1:'+server.address().port,cookie='';
 async function request(route,body,method='POST',extra={}){return fetch(base+route,{method,headers:{Origin:base,'X-Requested-With':'Steady','Content-Type':'application/json',Cookie:cookie,...extra},body:body===undefined?undefined:JSON.stringify(body)})}
 try {
  assert.equal((await request('/api/me',undefined,'GET')).status,401);
  const googleLanding=await fetch(base+'/api/auth/google',{headers:{Origin:base},redirect:'manual'});assert.equal(googleLanding.status,302);
 assert.equal((await request('/api/setup',{email:'bad@example.com',password:'long enough password' },'POST',{Origin:'https://attacker.example'})).status,403);
 assert.equal((await request('/api/setup',{email:'bad@example.com',password:'long enough password' },'POST',{'X-Requested-With':'','Origin':base})).status,403);

 const setups=await Promise.all([request('/api/setup',{email:'test@example.com',password:'long test password here'}),request('/api/setup',{email:'test@example.com',password:'long test password here'})]);assert.deepEqual(setups.map(x=>x.status).sort(),[200,409]);const setup=setups.find(x=>x.status===200);cookie=setup.headers.get('set-cookie').split(';')[0];
 assert.equal(setup.headers.get('set-cookie').includes('HttpOnly'),true);
 assert.equal((await request('/api/profile',{timezone:'UTC',onboardingComplete:true} ,'PUT')).status,200);
 assert.equal((await request('/api/checkin',{symptoms:'none',energy:'medium'})).status,200);
 assert.equal((await request('/api/plan/confirm',{})).status,200);
 const equipment=await request('/api/exercise-profiles',{exerciseName:'Treadmill',equipmentName:'Movati treadmill',loadMeaning:'total',setupNote:'Comfortable incline'});assert.equal(equipment.status,201);const equipmentId=(await equipment.json()).id;
 assert.equal((await request('/api/exercise-profiles/'+equipmentId,{setupNote:'Use handrails only for balance'},'PUT')).status,200);
 const data={exercises:[{name:'Treadmill',sets:[{duration:12,distance:0.8,incline:1,equipmentProfileId:equipmentId}]}]};
 assert.equal((await request('/api/workout',{data:{exercises:[{name:'Different exercise',sets:[{duration:12,equipmentProfileId:equipmentId}]}]},status:'active'})).status,400);
 const saved=await request('/api/workout',{data,status:'active'});assert.equal(saved.status,200);
 assert.equal((await request('/api/workout',{data,status:'active'})).status,409);
 let current=await (await request('/api/me',undefined,'GET')).json();assert.equal(current.workoutHistory[0].status,'active');
 assert.equal(current.exerciseProfiles[0].setupNote,'Use handrails only for balance');
 const withOneMore=structuredClone(current.workout);withOneMore.exercises[0].sets.push({duration:2,distance:0.1});assert.equal((await request('/api/workout',{data:withOneMore,version:current.workout.version,status:'active'})).status,200);
 current=await (await request('/api/me',undefined,'GET')).json();const undone=structuredClone(current.workout);undone.exercises[0].sets.pop();assert.equal((await request('/api/workout',{data:undone,version:current.workout.version,status:'active'})).status,200);
 current=await (await request('/api/me',undefined,'GET')).json();assert.equal(current.workout.exercises[0].sets.length,1);assert.equal(current.workout.exercises[0].sets[0].duration,12);
 const plannedNames=current.plan.exercises.map(exercise=>exercise.name),extra=structuredClone(current.workout);extra.exercises.push({name:'Cable curl',pattern:'strength',unplanned:true,sets:[{weight:10,reps:12}]});assert.equal((await request('/api/workout',{data:extra,version:current.workout.version,status:'active'})).status,200);
 current=await (await request('/api/me',undefined,'GET')).json();assert.deepEqual(current.plan.exercises.map(exercise=>exercise.name),plannedNames);assert.equal(current.workout.exercises.at(-1).unplanned,true);
 const pixel='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADUlEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC';
 const uploaded=await request('/api/uploads',{data:'data:image/png;base64,'+pixel,day:'2026-09-23',caption:'Private test'});assert.equal(uploaded.status,201);const image=await uploaded.json();
 assert.equal((await request('/api/uploads/'+image.id,undefined,'GET')).status,200);
 assert.equal((await request('/api/uploads/'+image.id,{caption:'Updated caption'},'PUT')).status,200);
 assert.equal((await (await request('/api/uploads',undefined,'GET')).json()).uploads[0].caption,'Updated caption');
 assert.equal((await request('/api/uploads',{data:'data:image/png;base64,AAAA',day:'2026-09-23'})).status,400);
 assert.equal((await request('/api/uploads/'+image.id,undefined,'DELETE')).status,200);
 assert.equal((await request('/api/plan/confirm',{})).status,409);
 await new Promise(resolve=>server.close(resolve));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;
 const me=await (await request('/api/me',undefined,'GET')).json();assert.equal(me.workout.exercises[0].sets[0].duration,12);
 const review={day:'2026-09-23',workout:'planned rest',cardio:'not planned',food:'partly',energy:'medium',soreness:'none',steps:'',weight:'100',weightUnit:'kg',waist:'42',waistUnit:'in',systolic:'',diastolic:'',notes:'=HYPERLINK("https://example.com")'};
 assert.equal((await request('/api/day-review',review,'PUT')).status,200);
 assert.equal((await request('/api/day-review',review,'PUT')).status,409);
 assert.equal((await request('/api/measurements',{kind:'weight',value:101,unit:'kg',measuredDay:'2026-09-23'})).status,200);
 assert.equal((await request('/api/measurements',{kind:'weight',value:101,unit:'kg',measuredDay:'2026-09-25'})).status,400);
 assert.equal((await request('/api/measurements',{kind:'blood-pressure',value:120,unit:'lb',measuredDay:'2026-09-23'})).status,400);
 const progress=await (await request('/api/progress',undefined,'GET')).json();assert.equal(progress.reviews[0].steps,null);assert.equal(progress.reviews[0].weight,100);assert.equal(progress.trend.days,1);
 assert.equal((await request('/api/food-log',{day:'2026-09-23',meal:'snack',item:'Banana',portion:'one'})).status,200);
 assert.equal((await request('/api/sleep',{day:'2026-09-23',hours:7.5,quality:'good'})).status,200);
 assert.equal((await request('/api/activity',{day:'2026-09-23',kind:'walk',duration:30,steps:4500})).status,200);
 assert.equal((await request('/api/activity',{day:'2026-09-25',kind:'walk',steps:1000})).status,400);
 assert.equal((await request('/api/sleep',{day:'2026-09-25',hours:7,quality:'good'})).status,400);
 const activity=await (await request('/api/progress',undefined,'GET')).json();assert.equal(activity.foodLogs[0].item,'Banana');assert.equal(activity.sleepLogs[0].hours,7.5);assert.equal(activity.activitySummary.steps.average,4500);assert.equal(activity.activitySummary.steps.days,1);assert.equal(activity.activitySummary.activityMinutes.total,42);
 assert.equal((await request('/api/food-log',{day:'2026-09-25',meal:'snack',item:'Future'})).status,400);
 assert.equal((await request('/api/foods',{name:'Oats',category:'Carbohydrates'})).status,200);let foods=(await (await request('/api/me',undefined,'GET')).json()).foods;const oats=foods.find(x=>x.name==='Oats');assert.equal(oats.available,1);
 assert.equal((await request('/api/foods/'+oats.id,{name:'Steel-cut oats',category:'Carbohydrates',preference:'limited',notes:'Plain',available:false},'PUT')).status,200);foods=(await (await request('/api/me',undefined,'GET')).json()).foods;assert.equal(foods.find(x=>x.id===oats.id).available,0);assert.equal(foods.find(x=>x.id===oats.id).preference,'limited');
 assert.equal((await request('/api/foods',{name:'Banana',category:'Fruit'})).status,200);const banana=(await (await request('/api/me',undefined,'GET')).json()).foods.find(x=>x.name==='Banana');
 const favourite=await request('/api/meal-favourites',{name:'Quick snack',meal:'snack',foodIds:[banana.id],portion:'One banana'});assert.equal(favourite.status,201);const favouriteId=(await favourite.json()).id;
 assert.deepEqual((await (await request('/api/me',undefined,'GET')).json()).mealFavourites[0].foodIds,[banana.id]);
 assert.equal((await request('/api/foods/'+banana.id,{name:'Banana',category:'Fruit',preference:'preferred',notes:'',available:false},'PUT')).status,200);
 assert.equal((await request('/api/meal-favourites/'+favouriteId,{name:'Quick snack',meal:'snack',foodIds:[banana.id],portion:'One banana'},'PUT')).status,400);
 assert.equal((await request('/api/meal-favourites/'+favouriteId,undefined,'DELETE')).status,200);
 const csv=await (await request('/api/export.csv',undefined,'GET')).text();assert.match(csv,/"'=HYPERLINK/);assert.match(csv,/"set"/);
 const printable=await request('/api/print-summary',undefined,'GET');assert.equal(printable.status,200);assert.match(await printable.text(),/Steady progress summary/);
 assert.equal((await request('/api/logout',{})).status,200);
 assert.equal((await request('/api/me',undefined,'GET')).status,401);
 for(let i=0;i<8;i++)assert.equal((await request('/api/login',{email:'throttle@example.com',password:'wrong credentials'})).status,401);
 assert.equal((await request('/api/login',{email:'throttle@example.com',password:'wrong credentials'})).status,429);
  assert.equal((await request('/api/login',{email:'other@example.com',password:'wrong credentials'},'POST',{Origin:'https://attacker.example'})).status,403);
  const relogin=await request('/api/login',{email:'test@example.com',password:'long test password here'});assert.equal(relogin.status,200);cookie=relogin.headers.get('set-cookie').split(';')[0];
  assert.equal((await request('/api/logout-all',{})).status,200);assert.equal((await request('/api/me',undefined,'GET')).status,401);
 }finally{await new Promise(resolve=>server.close(resolve))}
});
