import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 3030);
const SECRET = process.env.SESSION_SECRET || 'local-development-only-change-me';
const DATA = path.join(ROOT, 'data'); fs.mkdirSync(DATA, { recursive: true });
const UPLOADS = path.join(DATA, 'uploads'); fs.mkdirSync(UPLOADS, { recursive: true, mode: 0o700 });
const db = new DatabaseSync(path.join(DATA, 'fitness.sqlite'));
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS profiles(user_id INTEGER PRIMARY KEY REFERENCES users(id), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS checkins(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, data TEXT NOT NULL, UNIQUE(user_id, day));
CREATE TABLE IF NOT EXISTS plans(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, data TEXT NOT NULL, status TEXT NOT NULL, UNIQUE(user_id, day));
CREATE TABLE IF NOT EXISTS workouts(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, data TEXT NOT NULL, status TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(user_id, day));
CREATE TABLE IF NOT EXISTS measurements(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, kind TEXT NOT NULL, value REAL NOT NULL, unit TEXT NOT NULL, measured_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS foods(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, preference TEXT NOT NULL, notes TEXT DEFAULT '');`);
db.exec(`CREATE TABLE IF NOT EXISTS food_logs(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, meal TEXT NOT NULL, item TEXT NOT NULL, portion TEXT DEFAULT '', notes TEXT DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sleep_logs(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, hours REAL, quality TEXT, notes TEXT DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity_logs(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, kind TEXT NOT NULL, duration INTEGER, distance REAL, steps INTEGER, notes TEXT DEFAULT '', created_at TEXT NOT NULL);`);
db.exec(`CREATE TABLE IF NOT EXISTS uploads(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, day TEXT NOT NULL, filename TEXT NOT NULL, mime TEXT NOT NULL, bytes INTEGER NOT NULL, caption TEXT DEFAULT '', created_at TEXT NOT NULL);`);

const now = () => new Date().toISOString();
const dayFor = (tz = 'UTC') => new Intl.DateTimeFormat('en-CA', { timeZone: tz, year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date());
const hash = (v) => crypto.createHash('sha256').update(v).digest('hex');
const send = (res, status, body, type='application/json') => { res.writeHead(status, {'Content-Type': type, 'Cache-Control':'no-store'}); res.end(type==='application/json' ? JSON.stringify(body) : body); };
const json = async (req) => { let s=''; for await (const c of req) s+=c; return s ? JSON.parse(s) : {}; };
const parseCookies = (s='') => Object.fromEntries(s.split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}));
const sessionUser = (req) => { const token=parseCookies(req.headers.cookie).session; if(!token) return null; const row=db.prepare('SELECT user_id,expires_at FROM sessions WHERE token_hash=?').get(hash(token)); if(!row || row.expires_at<Date.now()) return null; return row.user_id; };
const requireUser = (req,res) => { const id=sessionUser(req); if(!id) { send(res,401,{error:'Sign in required'}); return null; } return id; };
const passwordHash = (p) => { const salt=crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(p,salt,64).toString('hex')}`; };
const passwordOk = (p, stored) => { const [salt,key]=stored.split(':'); if(!salt||!key) return false; return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(p,salt,64)); };
const profileDefaults = { timezone:'America/Toronto', heightCm:180, weightLb:255, units:'lb', schedule:3, duration:60, gym:'Movati', experience:'beginner', equipment:'commercial gym', injuries:'', restrictions:'', foods:['Lean ground beef','Chicken breast','Oats','Yogurt','Bananas','Egg whites','Sweet potatoes','Costco vegetable mix','Costco root vegetable mix'] };
function planFor(check, profile, day) {
  const c=check||{}; const urgent=(Number(c.systolic)>=180||Number(c.diastolic)>=120) || ['chest-pain','fainting','severe-breathlessness'].includes(c.symptoms);
  if(urgent) return {kind:'safety-stop', title:'Pause exercise and get medical guidance', reason:'Your check-in includes a reading or symptom that should be assessed before exercise.', exercises:[], cardio:null, safety:'If symptoms are present, seek urgent care now. If a blood-pressure reading is 180/120 or higher, rest and repeat it; seek urgent medical help immediately if symptoms occur, and contact a clinician promptly even without symptoms.'};
  const low=c.energy==='low'||c.soreness==='high'||c.pain==='movement-pain'; const mins=Number(c.minutes||profile.duration||60); const base=low?2:3; const exercises=[{name:'Leg press or sit-to-stand',pattern:'squat',muscles:'legs',sets:base,reps:'8–12',rest:'90 sec',cue:'Brace gently, move with control, exhale as you stand.',alternatives:'Goblet squat to a box; preserve the squat pattern.'},{name:'Chest press or incline push-up',pattern:'push',muscles:'chest/shoulders',sets:base,reps:'8–12',rest:'90 sec',cue:'Keep shoulders comfortable; exhale as you press.',alternatives:'Machine chest press or wall push-up.'},{name:'Seated row',pattern:'pull',muscles:'back',sets:base,reps:'8–12',rest:'90 sec',cue:'Pull elbows toward ribs; do not hold your breath.',alternatives:'Cable row with a comfortable grip.'}];
  if(mins>=60&&!low) exercises.push({name:'Treadmill walk',pattern:'cardio',muscles:'cardiorespiratory',sets:1,reps:'15–25 min',rest:'as needed',settings:{speed:'comfortable speaking pace',incline:'0–3%',effort:'moderate; talk in short sentences'},cue:'Start easy for 5 minutes, then use a comfortable speaking pace. Reduce speed or incline if symptoms, unusual breathlessness, dizziness, or pain occur.',alternatives:'Easy bike or outdoor walk.'});
  return {kind:low?'recovery-strength':'strength', title:low?'Steady recovery session':'Full-body strength + moderate cardio', reason:low?'Reduced volume because your check-in shows lower readiness.':'A repeatable full-body session supports consistency without requiring maximal effort.', exercises:mins<40?exercises.slice(0,2):exercises, cardio:mins<60?'10–15 min easy walk':'15–25 min moderate walk', safety:'Warm up 5 minutes, breathe continuously, stop for chest pain, fainting, severe dizziness, unusual shortness of breath, or movement-related pain.'};
}
async function route(req,res) {
  const u=new URL(req.url,`http://${req.headers.host}`), method=req.method;
  if(method==='GET' && (u.pathname==='/'||u.pathname==='/index.html')) return send(res,200,fs.readFileSync(path.join(ROOT,'public','index.html'),'utf8'),'text/html; charset=utf-8');
  if(method==='GET' && u.pathname.startsWith('/static/')) { const f=path.join(ROOT,'public',u.pathname.slice(8)); if(fs.existsSync(f)) return send(res,200,fs.readFileSync(f),f.endsWith('.css')?'text/css':'application/javascript'); return send(res,404,{error:'Not found'}); }
  if(method==='GET' && u.pathname==='/api/status') { const user=sessionUser(req); return send(res,200,{authenticated:!!user, hasUser:!!db.prepare('SELECT 1 FROM users LIMIT 1').get()}); }
  if(method==='POST' && u.pathname==='/api/setup') { if(db.prepare('SELECT 1 FROM users LIMIT 1').get()) return send(res,409,{error:'Account already exists'}); const b=await json(req); if(!b.email||!b.password||b.password.length<12) return send(res,400,{error:'Use an email and a password of at least 12 characters'}); const info=db.prepare('INSERT INTO users(email,password_hash,created_at) VALUES(?,?,?)').run(b.email.toLowerCase(),passwordHash(b.password),now()); db.prepare('INSERT INTO profiles(user_id,data) VALUES(?,?)').run(info.lastInsertRowid,JSON.stringify({...profileDefaults,...b.profile})); return login(res,info.lastInsertRowid); }
  if(method==='POST' && u.pathname==='/api/login') { const b=await json(req), row=db.prepare('SELECT * FROM users WHERE email=?').get((b.email||'').toLowerCase()); if(!row||!passwordOk(b.password||'',row.password_hash)) return send(res,401,{error:'Invalid email or password'}); return login(res,row.id); }
  if(method==='POST' && u.pathname==='/api/logout') { const token=parseCookies(req.headers.cookie).session; if(token) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token)); res.setHeader('Set-Cookie','session=; Max-Age=0; HttpOnly; SameSite=Lax; Path=/'); return send(res,200,{ok:true}); }
  const uid=requireUser(req,res); if(!uid) return;
  if(method==='GET' && u.pathname==='/api/me') { const p=db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid); const tz=(p?JSON.parse(p.data):profileDefaults).timezone||'UTC', day=dayFor(tz); const check=db.prepare('SELECT data FROM checkins WHERE user_id=? AND day=?').get(uid,day); const plan=db.prepare('SELECT data,status FROM plans WHERE user_id=? AND day=?').get(uid,day); const workout=db.prepare('SELECT data,status FROM workouts WHERE user_id=? AND day=?').get(uid,day); const measures=db.prepare('SELECT kind,value,unit,measured_at FROM measurements WHERE user_id=? ORDER BY measured_at DESC LIMIT 60').all(uid); const foods=db.prepare('SELECT * FROM foods WHERE user_id=? ORDER BY name').all(uid); const foodLogs=db.prepare('SELECT * FROM food_logs WHERE user_id=? AND day=? ORDER BY id DESC').all(uid,day); const sleep=db.prepare('SELECT * FROM sleep_logs WHERE user_id=? AND day=? ORDER BY id DESC LIMIT 1').get(uid,day); const activities=db.prepare('SELECT * FROM activity_logs WHERE user_id=? AND day=? ORDER BY id DESC').all(uid,day); const workoutHistory=db.prepare('SELECT day,data,status FROM workouts WHERE user_id=? AND status="completed" ORDER BY day DESC LIMIT 30').all(uid); return send(res,200,{profile:p?JSON.parse(p.data):profileDefaults,day,check:check?JSON.parse(check.data):null,plan:plan?{...JSON.parse(plan.data),status:plan.status}:null,workout:workout?{...JSON.parse(workout.data),status:workout.status}:null,measures,foods,foodLogs,sleep,activities,workoutHistory}); }
  if(method==='PUT' && u.pathname==='/api/profile') { const b=await json(req); db.prepare('UPDATE profiles SET data=? WHERE user_id=?').run(JSON.stringify({...profileDefaults,...b}),uid); return send(res,200,{ok:true}); }
  if(method==='POST' && u.pathname==='/api/checkin') { const b=await json(req), p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data), day=b.day||dayFor(p.timezone); db.prepare('INSERT INTO checkins(user_id,day,data) VALUES(?,?,?) ON CONFLICT(user_id,day) DO UPDATE SET data=excluded.data').run(uid,day,JSON.stringify(b)); let existing=db.prepare('SELECT status FROM plans WHERE user_id=? AND day=?').get(uid,day); if(!existing||existing.status==='unstarted') db.prepare('INSERT INTO plans(user_id,day,data,status) VALUES(?,?,?,?) ON CONFLICT(user_id,day) DO UPDATE SET data=excluded.data,status=excluded.status').run(uid,day,JSON.stringify(planFor(b,p,day)),'unstarted'); return send(res,200,{ok:true,day}); }
  if(method==='POST' && u.pathname==='/api/plan/confirm') { const p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data), day=dayFor(p.timezone), c=db.prepare('SELECT data FROM checkins WHERE user_id=? AND day=?').get(uid,day); if(!c) return send(res,400,{error:'Complete today’s check-in first'}); const plan=planFor(JSON.parse(c.data),p,day); db.prepare('INSERT INTO plans(user_id,day,data,status) VALUES(?,?,?,?) ON CONFLICT(user_id,day) DO UPDATE SET data=excluded.data,status=excluded.status').run(uid,day,JSON.stringify(plan),'confirmed'); return send(res,200,{ok:true,plan:{...plan,status:'confirmed'}}); }
  if(method==='POST' && u.pathname==='/api/workout') { const b=await json(req), p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data), day=b.day||dayFor(p.timezone); const existing=db.prepare('SELECT id FROM workouts WHERE user_id=? AND day=?').get(uid,day); if(existing) db.prepare('UPDATE workouts SET data=?,status=?,updated_at=? WHERE id=?').run(JSON.stringify(b.data),b.status||'active',now(),existing.id); else db.prepare('INSERT INTO workouts(user_id,day,data,status,updated_at) VALUES(?,?,?,?,?)').run(uid,day,JSON.stringify(b.data),b.status||'active',now()); return send(res,200,{ok:true,savedAt:now()}); }
  if(method==='POST' && u.pathname==='/api/measurements') { const b=await json(req); if(!['weight','waist','blood-pressure'].includes(b.kind)||!Number.isFinite(Number(b.value))) return send(res,400,{error:'Invalid measurement'}); db.prepare('INSERT INTO measurements(user_id,kind,value,unit,measured_at) VALUES(?,?,?,?,?)').run(uid,b.kind,Number(b.value),String(b.unit||''),b.measuredAt||now()); return send(res,200,{ok:true}); }
  if(method==='POST' && u.pathname==='/api/foods') { const b=await json(req); if(!b.name) return send(res,400,{error:'Food name required'}); db.prepare('INSERT INTO foods(user_id,name,category,preference,notes) VALUES(?,?,?,?,?)').run(uid,b.name,b.category||'Other',b.preference||'preferred',b.notes||''); return send(res,200,{ok:true}); }
  if(method==='POST' && u.pathname==='/api/food-log') { const b=await json(req); if(!b.item||!b.meal) return send(res,400,{error:'Meal and food are required'}); const p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data); db.prepare('INSERT INTO food_logs(user_id,day,meal,item,portion,notes,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,b.day||dayFor(p.timezone),b.meal,b.item,b.portion||'',b.notes||'',now()); return send(res,200,{ok:true}); }
  if(method==='POST' && u.pathname==='/api/sleep') { const b=await json(req); const hours=Number(b.hours); if(!Number.isFinite(hours)||hours<0||hours>24) return send(res,400,{error:'Sleep hours must be between 0 and 24'}); const p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data); db.prepare('INSERT INTO sleep_logs(user_id,day,hours,quality,notes,created_at) VALUES(?,?,?,?,?,?)').run(uid,b.day||dayFor(p.timezone),hours,b.quality||'okay',b.notes||'',now()); return send(res,200,{ok:true}); }
  if(method==='POST' && u.pathname==='/api/activity') { const b=await json(req); if(!b.kind) return send(res,400,{error:'Activity type required'}); const p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data); db.prepare('INSERT INTO activity_logs(user_id,day,kind,duration,distance,steps,notes,created_at) VALUES(?,?,?,?,?,?,?,?)').run(uid,b.day||dayFor(p.timezone),b.kind,b.duration?Number(b.duration):null,b.distance?Number(b.distance):null,b.steps?Number(b.steps):null,b.notes||'',now()); return send(res,200,{ok:true}); }
  if(method==='GET' && u.pathname==='/api/uploads') { const rows=db.prepare('SELECT id,day,mime,bytes,caption,created_at FROM uploads WHERE user_id=? ORDER BY created_at DESC').all(uid); return send(res,200,{uploads:rows}); }
  if(method==='POST' && u.pathname==='/api/uploads') { const b=await json(req); const raw=String(b.data||''); const m=raw.match(/^data:(image\/(?:png|jpeg|jpg));base64,(.+)$/i); if(!m) return send(res,400,{error:'Upload a PNG or JPEG image'}); const mime=m[1].toLowerCase()==='image/jpg'?'image/jpeg':m[1].toLowerCase(); let buf; try{buf=Buffer.from(m[2],'base64')}catch{return send(res,400,{error:'Invalid image encoding'})}; if(buf.length<16||buf.length>5*1024*1024) return send(res,400,{error:'Image must be between 16 bytes and 5 MB'}); const png=buf.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])); const jpg=buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff; if((mime==='image/png'&&!png)||(mime==='image/jpeg'&&!jpg)) return send(res,400,{error:'Image content does not match its declared type'}); const p=JSON.parse(db.prepare('SELECT data FROM profiles WHERE user_id=?').get(uid).data); const filename=`${crypto.randomBytes(24).toString('hex')}.${mime==='image/png'?'png':'jpg'}`; fs.writeFileSync(path.join(UPLOADS,filename),buf,{flag:'wx',mode:0o600}); const info=db.prepare('INSERT INTO uploads(user_id,day,filename,mime,bytes,caption,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,b.day||dayFor(p.timezone),filename,mime,buf.length,String(b.caption||'').slice(0,240),now()); return send(res,201,{id:info.lastInsertRowid,day:b.day||dayFor(p.timezone),mime,bytes:buf.length}); }
  if(method==='GET' && u.pathname.startsWith('/api/uploads/')) { const id=Number(u.pathname.split('/').pop()); const row=db.prepare('SELECT filename,mime FROM uploads WHERE id=? AND user_id=?').get(id,uid); if(!row) return send(res,404,{error:'Image not found'}); const file=path.join(UPLOADS,row.filename); if(!fs.existsSync(file)) return send(res,404,{error:'Image not found'}); res.writeHead(200,{'Content-Type':row.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}); return res.end(fs.readFileSync(file)); }
  if(method==='DELETE' && u.pathname.startsWith('/api/uploads/')) { const id=Number(u.pathname.split('/').pop()); const row=db.prepare('SELECT filename FROM uploads WHERE id=? AND user_id=?').get(id,uid); if(!row) return send(res,404,{error:'Image not found'}); db.prepare('DELETE FROM uploads WHERE id=? AND user_id=?').run(id,uid); try{fs.rmSync(path.join(UPLOADS,row.filename),{force:true})}catch{} return send(res,200,{ok:true}); }
  if(method==='DELETE' && u.pathname.startsWith('/api/foods/')) { db.prepare('DELETE FROM foods WHERE id=? AND user_id=?').run(Number(u.pathname.split('/').pop()),uid); return send(res,200,{ok:true}); }
  if(method==='GET' && u.pathname==='/api/export.csv') { const rows=db.prepare('SELECT day,data FROM checkins WHERE user_id=? ORDER BY day').all(uid); let out='date,check_in\n'; for(const r of rows) out+=`${r.day},${csv(r.data)}\n`; res.writeHead(200,{'Content-Type':'text/csv','Content-Disposition':'attachment; filename=fitness-progress.csv','Cache-Control':'no-store'}); return res.end(out); }
  send(res,404,{error:'Not found'});
}
function csv(v){return `"${String(v).replaceAll('"','""')}"`};
function login(res,id){const t=crypto.randomBytes(32).toString('base64url'); db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(t),id,Date.now()+1000*60*60*24*30); res.setHeader('Set-Cookie',`session=${encodeURIComponent(t)}; Max-Age=2592000; HttpOnly; SameSite=Lax; Path=/`); return send(res,200,{ok:true});}
const server=http.createServer((req,res)=>route(req,res).catch(e=>send(res,500,{error:'Request failed'}))); server.listen(PORT,()=>console.log(`Fitness tracker listening on http://localhost:${PORT}`));
export { planFor, dayFor, passwordHash, passwordOk };
