import {test,expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';
test('phone workout feedback persists after refresh and outlook does not log records',async({page})=>{
 const root=process.env.FITNESS_PUBLIC_ROOT||path.resolve(import.meta.dirname,'../../public');const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));let writes=0;
 const state:any={day:'2026-10-04',profile:{onboardingComplete:true,timezone:'America/Toronto',units:'lb',preferredDays:[1,3,5],schedule:3},check:{energy:'high'},foods:[],measures:[],workoutHistory:[],exerciseProfiles:[],foodLogs:[],activities:[],plan:{kind:'strength',title:'Test saved plan',reason:'Saved plan',safety:'Use comfortable effort',status:'active',exercises:[{name:'Seated row',pattern:'pull',sets:1,reps:'8–12',rest:'90 sec',muscles:'back'}]},workout:{status:'active',version:'v1',exercises:[{name:'Seated row',pattern:'pull',slot:0,sets:[{weight:10,reps:10,unit:'lb',done:true}]}]}};
 await page.setViewportSize({width:390,height:844});await page.route('**/tracker-coach',route=>route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')}));
 await page.route('**/static/**',route=>{const name=new URL(route.request().url()).pathname.split('/').pop()!,file=path.join(root,name);return fs.existsSync(file)?route.fulfill({contentType:name.endsWith('.css')?'text/css':name.endsWith('.svg')?'image/svg+xml':'text/javascript',body:fs.readFileSync(file)}):route.abort()});
 await page.route('**/api/**',route=>{const url=new URL(route.request().url());if(route.request().method()!=='GET'){writes++;const body=route.request().postDataJSON();expect(url.pathname).toBe('/api/workout');expect(body.version).toBe('v1');expect(body.data.exercises[0].sets[0].weight).toBe(10);state.workout={...body.data,status:body.status,version:'v2'};}return route.fulfill({json:url.pathname==='/api/me'?state:{}})});
 await page.goto('/tracker-coach');await expect(page.getByRole('button',{name:'Review and finish'})).toBeVisible();await page.getByText('Your next five days',{exact:true}).click();await expect(page.locator('.training-outlook li')).toHaveCount(5);expect(writes).toBe(0);
 await page.getByRole('button',{name:'Review and finish'}).click();await page.getByLabel('How did this session feel? (optional)').selectOption('too-hard');await page.getByRole('button',{name:'Finish workout',exact:true}).click();await expect(page.locator('.training-outlook')).toContainText('Saved session feedback: Too hard');expect(writes).toBe(1);await page.reload();await expect(page.locator('.training-outlook')).toContainText('Too hard');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}expect(errors).toEqual([]);
});
