import {test,expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';
test('Fitdays navigation, goals, details, sharing and refresh work on mobile',async({page})=>{
 const root=path.resolve(import.meta.dirname, '../../public');const policy=fs.readFileSync(path.join(root,'../workout-days.js'),'utf8').match(/res.setHeader\('Content-Security-Policy', "([^"]+)"\)/)?.[1];expect(policy).toBeTruthy();let fail=false,requests=0,countsOnly=false,today="2026-10-04";await page.clock.install();
 await page.route('**/fitdays-preview',route=>route.fulfill({contentType:'text/html',headers:{'Content-Security-Policy':policy!},body:fs.readFileSync(path.join(root,'fitdays.html'),'utf8')}));
 await page.route('**/static/fitdays*',route=>{const name=new URL(route.request().url()).pathname.split('/').pop()!;return route.fulfill({contentType:name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':name.endsWith('.webmanifest')?'application/manifest+json':'text/javascript',body:fs.readFileSync(path.join(root,name))})});
 await page.route('**/api/public-workout-days',route=>{requests++;return route.fulfill({status:fail?503:200,json:countsOnly?{today,visibility:'counts',counts:{week:1,month:2,year:3,calendarYear:2},insights:{week:{count:1,start:'2026-10-05',end:today},current:{count:1,start:'2026-10-01',end:today},currentComparable:{count:1,start:'2026-10-01',end:today},previousComparable:{count:2,start:'2026-09-01',end:'2026-09-05'},previousFull:{count:2}}}:{today,days:['2025-10-05','2026-09-03','2026-10-03']}})});
 await page.goto('/fitdays-preview');await page.getByText('Goals, trends and sharing',{exact:true}).click();await expect(page.locator('.month')).toHaveCount(1);await expect(page.locator('.month h3')).toHaveText('October 2026');await expect(page.locator('#yearCount')).toHaveText('3');
 await expect(page.locator('#monthlyRecap')).toContainText('1 recorded days');await expect(page.locator('#yearRecap')).toContainText('Partial calendar-year');await expect(page.locator('#weeklyHistory li')).toHaveCount(8);await page.getByText('Optional recorded-day challenge',{exact:true}).click();await page.locator('#challengeForm [name=start]').fill('2026-09-01');await page.locator('#challengeForm [name=end]').fill('2026-10-30');await page.locator('#challengeForm [name=target]').fill('12');await page.getByRole('button',{name:'Save challenge',exact:true}).click();await expect(page.locator('#challengeProgress')).toContainText('2 of 12');await page.locator('#challengeForm [name=paused]').check();await page.getByRole('button',{name:'Save challenge',exact:true}).click();await expect(page.locator('#challengeProgress')).toContainText('paused');await page.getByRole('button',{name:'Remove challenge',exact:true}).click();await expect(page.locator('#challengeProgress')).toContainText('No challenge');await page.getByRole('button',{name:'Preview this year’s summary'}).click();await expect(page.locator('#summaryPreview')).toBeVisible();await expect.poll(()=>page.locator('#summaryPreview').evaluate(image=>(image as HTMLImageElement).naturalWidth)).toBe(1080);await page.getByLabel('Optional monthly comparison target').fill('12');await page.getByLabel('Optional monthly comparison target').dispatchEvent('change');await expect(page.locator('#monthlyProgress')).toContainText('1 of 12');await page.getByLabel('Optional weekly comparison target').selectOption('3');await expect(page.locator('#weekProgress')).toContainText('1 of 3');await page.reload();await page.getByText('Goals, trends and sharing',{exact:true}).click();await expect(page.getByLabel('Optional weekly comparison target')).toHaveValue('3');await expect(page.getByLabel('Optional monthly comparison target')).toHaveValue('12');
 await page.getByRole('button',{name:'Previous month',exact:true}).click();await expect(page.locator('.month h3')).toHaveText('September 2026');await page.getByRole('button',{name:'Jump to today'}).click();await expect(page.locator('[aria-current="date"]')).toBeFocused();
 await page.getByRole('button',{name:/October 3, 2026.*workout completed/}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('#dayStatus')).toContainText('completed workout is recorded');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:/October 2, 2026.*no completion recorded/}).click();await expect(page.locator('#dayStatus')).toContainText('recovery day');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.getByLabel('Record window').selectOption('30');await expect(page.locator('#periodSummary')).toContainText('1 recorded days');await page.getByRole('button',{name:'Previous month',exact:true}).click();await expect(page.locator('.month-total')).toContainText('partial record window');await page.getByRole('button',{name:'Jump to today'}).click();const calendarDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download recorded dates (.ics)',exact:true}).click();const ics=await calendarDownload;expect(ics.suggestedFilename()).toBe('fitdays-30-days.ics');expect(fs.readFileSync((await ics.path())!,'utf8')).toContain('DTSTART;VALUE=DATE:20261003');await page.getByLabel('Record window').selectOption('365');await page.getByRole('button',{name:'Show full year'}).click();await expect(page.locator('.month')).toHaveCount(13);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)}
 await page.getByLabel('Summary image period').selectOption('30');await page.getByRole('button',{name:'Preview summary image'}).click();await expect(page.locator('#summaryPreview')).toBeVisible();await page.getByRole('button',{name:'Share summary image'}).click();await expect(page.getByRole('link',{name:'Download summary image'})).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download summary image'}).click();expect((await download).suggestedFilename()).toBe('fitdays-summary.png');
 await page.getByText('Add Fitdays to your iPhone Home Screen',{exact:true}).click();await expect(page.locator('.install-guide').filter({hasText:'Add Fitdays to your iPhone Home Screen'})).toContainText('Add to Home Screen');expect(await page.locator('link[rel="apple-touch-icon"]').getAttribute('href')).toContain('fitdays-icon-180.png');
 await expect(page.locator('#freshness')).toContainText('Updated');const before=requests;await page.evaluate(()=>{window.dispatchEvent(new Event('online'));window.dispatchEvent(new Event('pageshow'))});expect(requests).toBe(before);today='2026-10-05';await page.clock.fastForward(60000);await expect(page.locator('#updated')).toContainText('2026-10-05');expect(requests).toBe(before+1);
 fail=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('#updated')).toContainText('last loaded dates');await expect(page.locator('#freshness')).toContainText('Data may be stale');await expect(page.locator('.month')).toHaveCount(13);await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeEnabled();fail=false;countsOnly=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.day')).toHaveCount(0);await expect(page.locator('#dayTitle')).toHaveText('');expect(await page.locator('#dayDetail a').getAttribute('href')).toBe('https://fit.adeticket.com/');await expect(page.locator('.calendar-controls')).not.toBeVisible();await expect(page.locator('#exportCalendar')).not.toBeVisible();await expect(page.locator('#calendar')).toContainText('counts only');await expect(page.locator('#yearCount')).toHaveText('3');await expect(page.locator('#downloadSummary')).not.toBeVisible();
});

test('dated private History shortcut selects the date without writing records',async({page})=>{const root=path.resolve(import.meta.dirname,'../../public');let writes=0;await page.route('**/tracker-preview?**',route=>route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')}));await page.route('**/static/**',route=>{const name=new URL(route.request().url()).pathname.split('/').pop()!;const file=path.join(root,name);return fs.existsSync(file)?route.fulfill({contentType:name.endsWith('.css')?'text/css':name.endsWith('.svg')?'image/svg+xml':'text/javascript',body:fs.readFileSync(file)}):route.abort()});await page.route('**/api/**',route=>{const url=new URL(route.request().url());if(route.request().method()!=='GET')writes++;const body=url.pathname==='/api/me'?{day:'2026-10-07',profile:{onboardingComplete:true,timezone:'UTC',units:'lb',preferredDays:[]},foods:[],measures:[],workoutHistory:[],exerciseProfiles:[]}:url.pathname==='/api/progress'?{trend:{kg:null,days:0,sparse:true},measures:[],reviews:[],activities:[],workouts:[],foodLogs:[],sleepLogs:[]}:{};return route.fulfill({json:body})});await page.goto('/tracker-preview?historyDay=2026-10-05');await expect(page.locator('#view-history')).toBeVisible();await expect(page.locator('#measure').getByLabel('Measurement type')).toBeVisible();await expect(page.locator('#measure').getByLabel('Measurement value')).toBeVisible();await expect(page.locator('#measure').getByLabel('Measurement unit')).toBeVisible();await expect(page.locator('#view-history a[href="/api/export.csv"]')).toHaveCount(1);await expect(page.locator('#dayReview [name=day]')).toHaveValue('2026-10-05');await expect(page.locator('#pastWorkoutForm [name=day]')).toHaveValue('2026-10-05');expect(writes).toBe(0);await page.locator('[data-view=settings]').click();await expect(page.getByRole('heading',{name:'Private weekly schedule comparison'})).toBeVisible();await expect(page.getByText('Your preferred schedule is private and is not published on Fitdays.')).toBeVisible()});
